### PR TITLE
Fix a11y issues with the outdated warning

### LINKED ISSUE #129: Outdated warning doesn't meet a11y requirements
@michael-n-cooper mentioned the new warning on outdated specs is not accessible.
Color contrast should be updated and keyboard support added.

cc @plehegar

### PR DESCRIPTION
**Pull request by deniak**
That PR updates the outdated warning to follow the best the [WAI best practices for modal windows](https://www.w3.org/TR/wai-aria-practices-1.1/#dialog_modal).

It also fixes some contrast issues.

cc @michael-n-cooper @marcoscaceres @plehegar 

Fix #129

### CODE REVIEW

File: src/fixup.js [hunk 1]
```diff
@@ -158,6 +158,10 @@
       document.body.classList.add("outdated-spec");
       var node = document.createElement("p");
       node.classList.add("outdated-warning");
+      node.tabIndex = -1;
+      node.setAttribute("role", "dialog");
+      node.setAttribute("aria-modal", true);
```
Comment (marcoscaceres) [inline src/fixup.js]: Nit: explicitly string "true"

File: src/fixup.js [hunk 2]
```diff
@@ -158,6 +158,10 @@
...
+      node.setAttribute("aria-label", "outdatedWarning");
```
Comment (marcoscaceres) [inline src/fixup.js]: This should be two words... or better, "This specification is outdated!". Imagine this is being read out by the screen reader in this context. Only add the label if you really need it, and there is no other element already giving this information inside the node.

File: src/fixup.js [hunk 3]
```diff
@@ -194,7 +198,18 @@
...
+      button.focus();
+      window.onkeydown = function (event) {
+        if (event.keyCode == 27 && !node.classList.contains("outdated-collapsed")) button.click();
+      }
+      document.addEventListener("focus", function(event) {
+        if (!node.classList.contains("outdated-collapsed") && !node.contains(event.target)) {
+          event.stopPropagation();
+          node.focus();
+        }
+      }, true);
```
Comment (marcoscaceres) [inline src/fixup.js]: nit: why`true` here? If you really want to use capture, you should leave a comment why.

File: src/fixup.js [hunk 4]
```diff
@@ -194,7 +198,18 @@
...
         }
       }
+
       document.body.appendChild(node);
+      button.focus();
+      window.onkeydown = function (event) {
+        if (event.keyCode == 27 && !node.classList.contains("outdated-collapsed")) button.click();
+      }
+      document.addEventListener("focus", function(event) {
+        if (!node.classList.contains("outdated-collapsed") && !node.contains(event.target)) {
```
Comment (marcoscaceres) [inline src/fixup.js]: nit: easiest to read and maintain:

```JS
var containsTarget = node.contains(event.target);
var isCollapsed = node.classList.contains("outdated-collapsed");
if (!isCollapsed && !containsTarget) {
```

Also, might be misunderstanding, but don't you want to do this if it contains the target?

File: src/fixup.js [hunk 5]
```diff
@@ -194,7 +198,18 @@
           button.innerText = (isOpen) ? '\u25BE collapse' : '\u25B4 expand';
         }
       }
+
       document.body.appendChild(node);
+      button.focus();
+      window.onkeydown = function (event) {
+        if (event.keyCode == 27 && !node.classList.contains("outdated-collapsed")) button.click();
```
Comment (marcoscaceres) [inline src/fixup.js]: nit:  "===". Also, to avoid potential bugs later, add the "{" and "}" around the if; 

Might help to also do the following... for legibility:

```JS
var ESCAPEKEY = 27; // top of this file

if (event.keyCode === ESCAPEKEY && ...)
```

**Review by marcoscaceres — COMMENTED** [review]
Some feedback...

File: src/fixup.js (hunk 4 above)
Comment (deniak) [reply src/fixup.js]: The "Keyboard interaction" section from https://www.w3.org/TR/wai-aria-practices-1.1/#keyboard-interaction-6 says the focus should stay inside the dialog.
If the element isn't contained in the `node`, the code just focuses on the `node` itself.

Comment (marcoscaceres) [reply src/fixup.js]: Thanks for clarifying.

File: src/fixup.js (hunk 2 above)
Comment (deniak) [reply src/fixup.js]: Good point. In order to reuse the title we already have in the node, I changed the attribute from `aria-label` to `aria-labelledby`

File: src/fixup.js (hunk 3 above)
Comment (deniak) [reply src/fixup.js]: addressed

**Comment by deniak** [comment]
@marcoscaceres thanks for the review. I think I addressed all your comments.

File: src/fixup.js [hunk 6]
```diff
@@ -158,12 +159,17 @@
       document.body.classList.add("outdated-spec");
       var node = document.createElement("p");
       node.classList.add("outdated-warning");
+      node.tabIndex = -1;
+      node.setAttribute("role", "dialog");
+      node.setAttribute("aria-modal", "true");
+      node.setAttribute("aria-labelledby", "outdatedWarning");
```
Comment (marcoscaceres) [inline src/fixup.js:165]: nice!

File: src/fixup.js [hunk 7]
```diff
@@ -194,7 +200,24 @@
           button.innerText = (isOpen) ? '\u25BE collapse' : '\u25B4 expand';
         }
       }
+
       document.body.appendChild(node);
+      button.focus();
+      window.onkeydown = function (event) {
+        if (event.keyCode === ESCAPEKEY && !node.classList.contains("outdated-collapsed")) {
```
Comment (marcoscaceres) [inline src/fixup.js]: nit: you could also do here:

```
var isCollapsed = node.classList.contains("outdated-collapsed");
```

In case you need to add another thing to the if later.

File: src/fixup.js [hunk 8]
```diff
@@ -194,7 +200,24 @@
...
+
+      /* use capture to enable event delegation as focus doesn't bubble up */
+      document.addEventListener("focus", function(event) {
+        var isCollapsed = node.classList.contains("outdated-collapsed");
+        var containsTarget = node.contains(event.target);
+        if (!isCollapsed && !containsTarget) {
+          event.stopPropagation();
+          node.focus();
+        }
+      }, true);
```
Comment (marcoscaceres) [inline src/fixup.js]: the boolean trap remains unaddressed ?

Comment (marcoscaceres) [reply src/fixup.js]: ah, it's a the top!

Comment (marcoscaceres) [reply src/fixup.js]: be good to move the comment down here 😃

Comment (deniak) [reply src/fixup.js]: yeah, makes more sense :smiley:

File: src/fixup.js (hunk 7 above)
Comment (deniak) [reply src/fixup.js]: done

**Review by marcoscaceres — APPROVED** [review]
LGTM! Thanks for considering my feedback!

**Review by plehegar — APPROVED** [review]

**Review by plehegar — APPROVED** [review]

**Comment by deniak** [comment]
merged and deployed!
